version: '3.1'
services:
    app:
        build: docker/php-fpm/dev
        restart: on-failure
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.dev.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
            - './docker/php-fpm/php-ini-overrides.dev.ini:/etc/php/8.1/cli/conf.d/99-overrides.ini'
        environment:
            PHP_IDE_CONFIG: 'serverName=server'

    db_test:
        image: 'postgres'
        tmpfs: /var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=db_test
