version: '3.1'
services:
    postgres:
        image: 'postgres'
        restart: on-failure
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/postgresql_data:/var/lib/postgresql/data'

    webserver:
        image: 'nginx:alpine'
        restart: on-failure
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/logs:/var/log/nginx'